### ISSUE TITLE
URL in bgm setting for downloader.ini is not working.

### ISSUE THREAD

**Issue by EDDIE-X** [wizzomafizzo/MiSTer_BGM#12]
I tried to set the bgm setting to downloader.ini as stated in the readme file:

[bgm]
db_url = 'https://github.com/wizzomafizzo/MiSTer_BGM/blob/main/bgm.json'

But this gave me an error when running update_all.

I've found that the correct setting is:

[bgm]
db_url = 'https://raw.githubusercontent.com/wizzomafizzo/MiSTer_BGM/main/bgm.json'

I tested it and downloaded bgm.sh successfully.

Thanks.

**Comment by wizzomafizzo** [comment]
Thanks for reporting! I think I have fixed this now

**Comment by EDDIE-X** [comment]
Looks good, thank you very much for fixing the URL!
