### ISSUE TITLE
bgm.sh no longer working

### ISSUE THREAD

**Issue by andres-11** [wizzomafizzo/MiSTer_BGM#13]
Since update to Mister main 5/11th the script no longer appears to work. When running the script I get the following error

<pre>Traceback (most recent call last):
  File "/media/fat/Scripts/./bgm.sh", line 766, in <module>
    display_gui()
  File "/media/fat/Scripts/./bgm.sh", line 644, in display_gui
    status = get_status()
  File "/media/fat/Scripts/./bgm.sh", line 549, in get_status
    return send_socket("status").split("\t")
  File "/media/fat/Scripts/./bgm.sh", line 471, in send_socket
    s.connect(SOCKET_FILE)
ConnectionRefusedError: [Errno 111] Connection refused</pre>

Deleting bgm.ini the music folder and script and reinstalling does not resolve the issue

**Comment by wizzomafizzo** [comment]
Hi. What is the contents of the file user-startup.sh in the linux folder on your SD card?

**Comment by andres-11** [comment]
<pre>
#!/bin/sh

# Startup BGM
[[ -e /media/fat/Scripts/bgm.sh ]] && /media/fat/Scripts/bgm.sh $1
</pre>

**Comment by andres-11** [comment]
This issue can be closed as reinstalling my Mister OS resolved the issue
