### ISSUE TITLE
Script not persisting after cold boot

### ISSUE THREAD

**Issue by TonchMS** [wizzomafizzo/MiSTer_BGM#3]
The script seems to work just fine upon activation, stopping and starting appropriately. However it doesn't auto-start after a cold boot.

If I select one of the play/stop/skip scripts without re-running the main bgm script, it outputs something about there not being a "/tmp/bgm.sock" file or directory.

It works again if I run the main script, but I have to do this manually every time I cold boot the system.

**Comment by kairu43** [comment]
I can confirm this happens for me as well.

**Comment by wizzomafizzo** [comment]
Hi. Sounds like the mister startup script didn't get setup right. Can you please find the file from your SD card in the linux folder called user-startup.sh and post the contents here (/media/fat/linux/user-startup.sh if you ssh in)

**Comment by TonchMS** [comment]
Mine is actually there but with an underscore at the front of the filename (so presumably inactive), and that's it.

The only thing in it is

`#!/bin/sh

echo "***" $1 "***"
`

**Comment by kairu43** [comment]
#!/bin/sh

echo "***" $1 "***"

**Comment by wizzomafizzo** [comment]
Thank you. You both have an underscore in front?

I think I can fix this then. I assumed that appending to a file in Python would also create the file if it doesn't exist but apparently not

Try to rename that file without an underscore in front and see if that fixes it 

I can put in an update to fix automatically but not til tomorrow probably

**Comment by wizzomafizzo** [comment]
Oh and run bgm from the scripts menu after you rename it

**Comment by TonchMS** [comment]
This did fix it, although it runs pretty late, like 18 seconds after the main menu appears-- I'm not sure if that's just how it works or not.

**Comment by wizzomafizzo** [comment]
It does run quite late unfortunately although 18 seconds sounds a little longer than usual. I can't change it too much though I'm at the mercy of when mister launches that startup script

For reference mine usually kicks in just after the Bluetooth and wifi icons appear in the menu

**Comment by kairu43** [comment]
Yep, my filename is "_user-startup.sh" also.

I've renamed it, re-run the script and it seems to work fine for me. There's a moment where the tv-input handshakes with the Mister at the start of cold-boot, but once I see video, I also hear my _boot.wav track has begun playing.

Thanks :)

**Comment by kairu43** [comment]
For reference, I've just got two and it seems pretty instant ("Solar Sailer" as boot and the "End Titles" theme, both from Tron Legacy :) )

**Comment by wizzomafizzo** [comment]
> I wonder if it's because I have a ton of mp3s in that folder, maybe if I cull them it'd be faster.

It's certainly possible but I'd also expect you to have a significant delay in between tracks playing too! The script doesn't generate a playlist to run off, it just scans the whole directory every time and picks a random file. I might need to do some experimenting with different amounts of tracks in there

If that is the cause, I can probably put together something clever enough to avoid/hide this delay

**Comment by TonchMS** [comment]
There's definitely no delay when skipping tracks. And as you say, my tracks start playing when the wifi and Bluetooth icons appear, but for me that's about 18 seconds on average. I significantly reduced the number of tracks and it didn't make any noticeable difference. It might just be the way my device or card is configured. It's really not an enormous issue either way, now that it's at least working.

**Comment by TonchMS** [comment]
Anyway since we figured out the user-startup.sh issue and any other delays don't seem related to the script itself, I'll close this. Thanks for the script!

**Comment by wizzomafizzo** [comment]
Fix is in for this now. Thanks for your help
