### ISSUE TITLE
Add multiple music directories like wallpapers

### ISSUE THREAD

**Issue by onaryc** [wizzomafizzo/MiSTer_BGM#6]
It would be nice to play musics from specific directories according to the current mister ini file chosen (like wallpapers). I do not know if the information of which ini file has been chosen is available outside the Mister main though.

For example : 
music : files to be played for the main mister ini file
-> alt1 : files to be played for alt1 ini file
-> alt2 : files to be played for alt2 ini file
-> alt3 : files to be played for alt3 ini file

**Comment by wizzomafizzo** [comment]
Hi. Thanks for the suggestion. I had an idea for this in mind, separate sub folders in the music folder, and you could pick whatever folder in particular to play as a playlist. Is that like what you have in mind?

At first, you'd just set the folder to play in the bgm ini file but eventually I'd like to be able to change the playlist dynamically

**Comment by wizzomafizzo** [comment]
I've implemented this now in the latest version. Please give it a shot!
