### ISSUE TITLE
Add bgm_on and bgm_off scripts so I can enable/disable the service without editing user-startup.sh

### ISSUE THREAD

**Issue by spotanime** [wizzomafizzo/MiSTer_BGM#8]
Would love to just turn on/off the service through the MiSTer menu rather than through FTP/SSH and editing user-startup.sh directly.

**Comment by wizzomafizzo** [comment]
Hey. Thanks for the report. I actually added a feature (not on GitHub yet) to let you enable/disable starting on boot from the ini file but I can see now that isn't really going to fix your problem

I think what I'm going to do instead is get rid of the control scripts and make the main bgm script display a basic control GUI similar to my favorites script and the mister ini editor. So you'll be able to edit some ini options from there

This'll be a bit low down the todo list but keep an eye out cause I need to do it to prepare for my web remote idea

**Comment by wizzomafizzo** [comment]
This is supported now! Let me know how it goes
