### ISSUE TITLE
Add sub-directory support

### ISSUE THREAD

**Issue by KingKannibal** [wizzomafizzo/MiSTer_BGM#9]
I added a bunch of music but would prefer it if I could keep my music organized in sub directories instead of all of it in the same folder. I suggest at least about 2 to 3 directories deep from the music folder.

Ex. 1: music/Artist/Album/track.mp3
Ex. 2: music/Album/track.mp3

**Comment by wizzomafizzo** [comment]
Thanks for the suggestion. My latest update stopped this being possible a bit but I would still like to implement it. I'm planning on adding a couple of things:

- A meta "all" playlist which plays anything in any folder or subfolder
- Make it so playlist folders by default will include all their subfolders

So you can either use the "all" playlist to make this work or you can stick all your organised stuff in its own separate playlist folder. There won't be a limit on how deep the folders go unless we run into performance issues down the line. Bit it shouldn't really be a problem

**Comment by KingKannibal** [comment]
Thanks for acknowledging this. Looking forward to that in a future update :D

**Comment by wizzomafizzo** [comment]
This is in now! Let me know how you go

**Comment by KingKannibal** [comment]
It's working beautifully now, thanks!
